config/routes.rb
Studyr::Application.routes.draw do
  
  resources :admin

  resources :course_lessons
  
  resources :courses do
    resources :course_lessons
  end

  devise_for :users

  resources :class_resources

  resources :users do
    resources :notebooks
  end
  
  resources :notebooks do
    resources :lessons
  end
    
  match "/home", :to => "pages#home"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/profile", :to => "users#show"
  match "/lessons/shared", :to => "lessons#shared"
  match "/class-resources/my", :to => "class_resources#my"

   root :to => "pages#home"

end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :user
  has_many :lessons, :dependent => :destroy
  
  # send id & title as url param
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  # cancan authorize
  load_and_authorize_resource

  before_filter :authenticate_user!, :only => [:index, :new, :show, :edit, :update]
  # GET /notebooks
  # GET /notebooks.xml
  def index
    @user = current_user
    @notebooks = @user.notebooks.order("updated_at DESC")
    if @notebooks.length == 0
      @notebook = Notebook.new
    end
    @title = "My notebooks"
  end

  # GET /notebooks/1
  # GET /notebooks/1.xml
  def show
    @user = current_user
    @notebook = @user.notebooks.find(params[:id])
    @title = @notebook.name
    @lessons = @notebook.lessons
    if @lessons.length == 0 && current_user.id == @notebook.user_id
      redirect_to new_notebook_lesson_path(@notebook)
      return
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notebook }
    end
  end

  # GET /notebooks/new
  # GET /notebooks/new.xml
  def new
    #@user = current_user
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
    @user = current_user
    @notebook = @user.notebooks.find(params[:id])
  end

  # POST /notebooks
  # POST /notebooks.xml
  def create
    @notebook = current_user.notebooks.build(params[:notebook])
    
      if @notebook.save
        flash[:success] ="Saved a new notebook"
        redirect_to @notebook
      else
        render :action => "new" 
      end
  end

  # PUT /notebooks/1
  # PUT /notebooks/1.xml
  def update
    @user = current_user
    @notebook = @user.notebooks.find(params[:id])
    if @notebook.update_attributes(params[:notebook])
      flash[:notice] = "Successfully updated"
      redirect_to notebooks_path
    else
      render :action => "edit" 
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.xml
  def destroy
    @user = current_user
    @notebook = @user.notebooks.find(params[:id])
    @notebook.destroy

    respond_to do |format|
      format.html { redirect_to user_notebooks_path }
      format.js  { render :nothing => true }
    end
  end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_for([@user,@notebook]) do |f| %>
  <% if @notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% @notebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, t(:notebook_name) %><br />
    <%= f.text_field :name %>
  </div>
  <div class="prext ntbk-dt">
    <div class="ext-settings notebook-settings inactive">
      More about this notebook
    </div>
    <div class="field">
      <%= f.label :course, t(:course_code) %><br />
      <%= f.text_field :course %>
    </div>

    <div class="field">
      <%= f.label t(:lecturer) %><br />
      <%= f.text_field :lecturer %>
    </div>
  </div>


  <div class="save">
    <%= f.submit :class => "primary"%>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t 'edit_notebook', :notebook => @notebook.name %></h2>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>
<section class="pr_dash">
<%= render 'form' %>

<%= link_to t(:back), notebooks_path %>
</section>

app/views/notebooks/index.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :my_notebooks %></h2>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>
<section class="pr_dash">
  <%= link_to t(:new_notebook), new_notebook_path, :class => "new-notebook"%>
  <% if @notebooks.length > 0 %>
  <div id="notebooks">
    <% @notebooks.each_with_index do |notebook, key| %>
      <div class="notebook notebook-<%= key%2 %>">
        <h3 class="notebook-name">
          <%= link_to notebook.name, notebook_lessons_path(notebook), :class => "lesson-title" %>
        </h3>
        <div class="notebook-details-index">
          <div><%=t :lecturer %>: <%= notebook.lecturer %> </div> 
        </div>
        <%= link_to t(:new_lesson), new_notebook_lesson_path(notebook), :class => "new-lesson" %>
        <% @lessons = notebook.lessons.order("updated_at DESC") %>
        <% if @lessons.size > 0 %>
          <div class="notebook-lessons">
            <div class="lessons-title"><%=t :lessons %></div>
              <div class="lessons">
                <% @lessons.each do |lesson| %>
                  <div class="lesson"><%= link_to lesson.title, notebook_lesson_path(notebook, lesson) %> </div>
                <% end %>
              </div>
            </div>
        <% else %>
          <div class="notebook-lessons">
            <div class="lessons-title">
              <%=t :time_to_add_first_lesson %>: <br />
              <%= link_to t(:click_to_add_first_lesson), new_notebook_lesson_path(notebook), :class => "no-lessons" %></div>
          </div>
        <% end %>
        <div class="tools">
          <div class="edit-notebook"><%= link_to t(:edit_notebook), edit_user_notebook_path(@user, notebook), :title => "Edit notebook"  %></div>
          <div class="delete-notebook"><%= link_to t(:delete_notebook), notebook, :class =>"del-notebook", :method => :delete, :remote => true, confirm: 'Are you sure you want to delete this notebook?', :title => "Delete notebook" %></div>
        </div>
      </div>
    <% end %>
  </div>
  <% else %>
  <div class="clear-both">
    <%=t :nonotebooks_html %>
    <%= render 'form' %>
  </div> 
  <% end %>
</section>
</div>

app/views/notebooks/new.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :create_new_notebook %></h2>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>
<section class="pr_dash">
<%= render 'form' %>

<%= link_to t(:back), notebooks_path %>
</section>

app/views/notebooks/show.html.erb
<div class="banner lessons notebooks">
  <div class="container">
    <h2>
      <% if @lessons.empty? %>
        Create a first lesson
      <% else %>
        <%= @notebook.name %> lessons
      <%end%>
    </h2>
  </div>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="lessons_dash">
    <div class="notebook">
      <% if @lessons.empty? %>
        <%= render 'lessons/form' %>
      <% else %>
        <h1 class="notebook-name"><%= @notebook.name %></h1>
        <% @lessons.each do |lesson| %>
          <div><%= link_to lesson.title, notebook_lesson_path(@notebook, lesson) %></div> 
        <% end %>
      <% end %>
    </div>
  </div>
</div>