config/routes.rb
Studyr::Application.routes.draw do
  
  resources :admin

  resources :course_lessons
  
  resources :courses do
    resources :course_lessons
  end

  devise_for :users

  resources :class_resources

  resources :users do
    resources :notebooks
  end
  
  resources :notebooks do
    resources :lessons
  end
    
  match "/home", :to => "pages#home"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/profile", :to => "users#show"
  match "/lessons/shared", :to => "lessons#shared"
  match "/class-resources/my", :to => "class_resources#my"

   root :to => "pages#home"

end

app/models/course_lesson.rb
class CourseLesson < ActiveRecord::Base
  belongs_to :course
  
  has_many :videos, :dependent => :destroy
  accepts_nested_attributes_for :videos, :reject_if => lambda { |a| a[:link].blank? }, :allow_destroy => true
  
  validates :name, :presence => true
  validates :course_id, :presence => true
  validates :user_id, :presence => true
  
  mount_uploader :file, PresentationUploader
  
end

app/controllers/course_lessons_controller.rb
class CourseLessonsController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :show, :edit, :update, :destroy, :shared]
  
  before_filter :find_course, :only => [:new]
  # GET /course_lessons
  # GET /course_lessons.json
  def index
    @user = current_user
    @course = Course.find(params[:course_id])
    @course_lessons = @course.course_lessons.order("updated_at DESC")
    if @course_lessons.count == 0
      @course_lesson = CourseLesson.new
    end
    @title = @course.name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @course_lessons }
    end
  end

  # GET /course_lessons/1
  # GET /course_lessons/1.json
  def show
    #@course = Course.find(params[:course_id])
    @course_lesson = CourseLesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course_lesson }
    end
  end

  # GET /course_lessons/new
  # GET /course_lessons/new.json
  def new
    @user = current_user
    @course_lesson = CourseLesson.new
    3.times { @course_lesson.videos.build }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course_lesson }
    end
  end

  # GET /course_lessons/1/edit
  def edit
    @course = current_user.courses.find(params[:course_id])
    @course_lesson = @course.course_lessons.find(params[:id])
  end

  # POST /course_lessons
  # POST /course_lessons.json
  def create
    @course = current_user.courses.find(params[:course_id])
    @course_lesson = @course.course_lessons.build(params[:course_lesson])
    @course_lesson.user_id = @course.user_id

    respond_to do |format|
      if @course_lesson.save
        format.html { redirect_to profile_path, notice: 'Course lesson was successfully created.' }
        format.json { render json: @course_course_lesson, status: :created, location: @course_lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @course_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /course_lessons/1
  # PUT /course_lessons/1.json
  def update
    @course = current_user.courses.find(params[:course_id])
    @course_lesson = @course.course_lessons.find(params[:id])
    respond_to do |format|
      if @course_lesson.update_attributes(params[:course_lesson])
        format.html { redirect_to @course, notice: 'Course lesson was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_lessons/1
  # DELETE /course_lessons/1.json
  def destroy
    @course_lesson = CourseLesson.find(params[:id])
    @course_lesson.destroy

    respond_to do |format|
      format.html { redirect_to course_lessons_url }
      format.json { head :ok }
    end
  end
  
  protected
    def find_course
      if(params[:course_id])
        @course = current_user.courses.find(params[:course_id])
      end
    end
end

app/helpers/course_lessons_helper.rb
module CourseLessonsHelper
end

app/views/course_lessons/_form.html.erb
<%= javascript_include_tag 'bootstrap-tab.js' %>
<script>
$(function () {
  $('.nav a:first ').tab('show');
})
</script>
<%= form_for([@course, @course_lesson]) do |f| %>
  <% if @course_lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_lesson.errors.count, "error") %> prohibited this course_lesson from being saved:</h2>

      <ul>
      <% @course_lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label t(:lesson_name) %>
    <%= f.text_field :name %><br />
  </div>
  <ul id="tab" class="nav nav-tabs">
    <li><a href="#presentation" data-toggle="tab">Add presentation</a></li>
    <li><a href="#links" data-toggle="tab">Add links</a></li>
    <li><a href="#images" data-toggle="tab">Add images</a></li>
    <li><a href="#videos" data-toggle="tab">Add videos</a></li>
  </ul>
  <div id="myTabContent" class="tab-content">
    <div class="field" id="presentation">
      <%= f.file_field :file %>
    </div>
    <div class="field" id="links">
      Here I put links
    </div>
    <div class="field" id="images">
      Here I put images
    </div>
    <div class="field" id="videos">
      <%= f.fields_for :videos do |builder| %>
        <div class="videos">
          <%= builder.text_field :link %>
        </div>
      <% end %>
      <span class="description">e.g youtube: K_o2MZaM584</span>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_lessons/edit.html.erb
<h1>Editing course_lesson</h1>

<%= render 'form' %>

app/views/course_lessons/index.html.erb
<div class="banner lessons notebooks">
  <div class="container">
    <h2><%= @course.name %> lessons</h2>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>
<div class="lessons_dash">
  <div class="notebook">
  <h1 class="notebook-name"><%= @course.name %></h1>

  <% if @course_lessons.count > 0 %>
    <% if @current_user.id == @course.user_id %>
      <%= link_to 'new Lesson', new_course_course_lesson_path, :class => "new-lesson" %>
    <% end %>
    <h3 class="lessons-list">list of lessons</h3>
    <% @course_lessons.each do |lesson| %>
      <div class="lesson">  
        <h3 class="lesson-title"><%= link_to lesson.name, course_course_lesson_path(@course, lesson) %></h3>
        <%# if can? :update, lesson %>
        <div class="tools">
          <div class="edit-lesson"><%= link_to 'Edit lesson', edit_course_course_lesson_path(@course, lesson), :class =>"btn info", :title => "Edit lesson"  %></div>
          <div class="delete-lesson"><%= link_to '- Delete lesson', [@course, lesson], :class =>"del-lesson", :method => :delete, :remote => true, confirm: 'Are you sure you want to delete this lesson?', :title => "Delete lesson" %></div>
        </div>
        <% #end %>
      </div>
    <% end %>
  <% else %>
    <% if @current_user.id == @course.user_id %>
      <h3 class="lessons-list">Create a first lesson</h3>
      <%= link_to 'new Lesson', new_course_course_lesson_path, :class => "new-lesson" %>
    <% else %>
      No lessons created yet.
    <% end %>
  <% end %>
  </div>
</div>

app/views/course_lessons/new.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :new_lesson %></h2>
  </div>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <section class="pr_dash">
    <%= render 'form' %>
    <%= link_to 'Back', courses_path %>
  </section>
</div>

app/views/course_lessons/show.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%= @course_lesson.course.name %> / <%= @course_lesson.name %></h2>
  </div>
</div>
<div class="container">
  <section class="pr_dash">
    <%= link_to "File for presentation / download", @course_lesson.file.url %>

    <p>Sharing url</p> http://studyers.com/course_lessons/<%= @course_lesson.id %>

    <ul class="images media-grid">
      <% Dir["public/" + @course_lesson.file.store_dir + "/*.png"].each do |image| %>
        <% #Bad way to display - need to fix... %>
        <li><a href="#" class="one-slide"><%= image_tag(image[6..-1]) %></a></li>
      <% end %>
    </ul>
    <div>
      <% for video in @course_lesson.videos %>
        <div><%= sanitize video.link %></div>
      <% end %>
    </div>
  </section>
</div>