config/routes.rb
Studyr::Application.routes.draw do
  
  resources :admin

  resources :course_lessons
  
  resources :courses do
    resources :course_lessons
  end

  devise_for :users

  resources :class_resources

  resources :users do
    resources :notebooks
  end
  
  resources :notebooks do
    resources :lessons
  end
    
  match "/home", :to => "pages#home"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/profile", :to => "users#show"
  match "/lessons/shared", :to => "lessons#shared"
  match "/class-resources/my", :to => "class_resources#my"

   root :to => "pages#home"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # cancan authorize
  load_and_authorize_resource
  
  before_filter :authenticate_user!, :only => [:index, :new, :show, :edit, :update]
  
  # GET /courses
  # GET /courses.json
  def index
    @user = current_user
    @courses = @user.courses.order("updated_at DESC")
    if @courses.length == 0
      @course = Course.new
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @user = current_user
    ## Need to figure out here.... ##
    @course = Course.find(params[:id])
    @course_lessons = @course.course_lessons
    @title = @course.name
    if @course_lessons.length == 0 && current_user.id == @course.user_id
      redirect_to new_course_course_lesson_path(@course)
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @user = current_user
    @course = @user.courses.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @user = current_user
    @course = @user.courses.build(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @user = current_user
    @course = @user.courses.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = current_user.courses.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :term %><br />
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>
  <div class="actions save">
    <%= f.submit :class => "primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :edit_course %></h2>
  </div>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <section class="pr_dash">
    <%= render 'form' %>
    <%= link_to 'Back', courses_path %>
  </section>
</div>

app/views/courses/index.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :my_courses %></h2>
  </div>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <section class="pr_dash">



<% @courses.each do |course| %>
    <td><%= course.user_id %></td>
    <td><%= course.name %></td>
    <td><%= course.number %></td>
    <td><%= course.department %></td>
    <td><%= course.term %></td>
    <td><%= course.school %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
<% end %>



<%= link_to 'New Course', new_course_path %>
  </section>
</div>

app/views/courses/new.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%=t :new_course %></h2>
  </div>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <section class="pr_dash">
    <%= render 'form' %>
    <%= link_to 'Back', courses_path %>
  </section>
</div>

app/views/courses/show.html.erb
<div class="banner profile notebooks">
  <div class="container">
    <h2><%= @course.name %></h2>
  </div>
</div>
<div class="container">
  <section class="pr_dash">
    <div class="course-details">
      <% if !@course.number.empty? %><%= @course.number %> <% end %>
      <% if !@course.department.empty? %>| <%= @course.department %> <% end %>
      <% if !@course.term.empty? %> | <%= @course.term %><% end %>
    </div>

    <% if @course_lessons.length > 0 %>
    <ul>
    <% @course_lessons.each do |lesson| %>
      <li>
        <%= link_to lesson.name, course_course_lesson_path(@course, lesson) %> <br />
        <%= link_to "Edit #{lesson.name}", edit_course_course_lesson_path(@course, lesson) %>
      </li>-
    <% end %>
    </ul>
    <%= link_to "new lesson", new_course_course_lesson_path(@course) %>
  <% else %>
    No course lessons created yet. <br />
    <% if current_user.id == @course.user_id %>
      <%= link_to "Create a first lesson", new_course_course_lesson_path(@course) %>      
    <% end %>
  <% end %>
  </section>
</div>