config/routes.rb
Studyr::Application.routes.draw do
  
  resources :admin

  resources :course_lessons
  
  resources :courses do
    resources :course_lessons
  end

  devise_for :users

  resources :class_resources

  resources :users do
    resources :notebooks
  end
  
  resources :notebooks do
    resources :lessons
  end
    
  match "/home", :to => "pages#home"
  match "/about", :to => "pages#about"
  match "/contact", :to => "pages#contact"
  match "/profile", :to => "users#show"
  match "/lessons/shared", :to => "lessons#shared"
  match "/class-resources/my", :to => "class_resources#my"

   root :to => "pages#home"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    can :read, Lesson do |lesson|
      @user = User.find(lesson.try(:user_id))
      # If owner | if public | if friends & permission for friends.
      shared_ids = []
      shared_ids = Share.where("lesson_id = ?", lesson.id).map(&:shared_ids)
      lesson.try(:user_id) == user.id || shared_ids.include?(user.id.to_s) || lesson.try(:permission) == 1
    end
    
    #can :manage, Lesson do |lesson|
    #  lesson.try(:user_id) == user.id 
    #end
    
    can :manage, Lesson, :user_id => user.id
    
    can :read, Course
    can :manage, Course, :user_id => user.id ##&& user.role? == 'teacher'
    
    can :read, Notebook
    can :manage, Notebook, :user_id => user.id
    
  end
end

app/models/class_resource.rb
class ClassResource < ActiveRecord::Base
  mount_uploader :presentation, PresentationUploader
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many :course_lessons, :dependent => :destroy
  
  validates :name, :presence => true
end

app/models/course_lesson.rb
class CourseLesson < ActiveRecord::Base
  belongs_to :course
  
  has_many :videos, :dependent => :destroy
  accepts_nested_attributes_for :videos, :reject_if => lambda { |a| a[:link].blank? }, :allow_destroy => true
  
  validates :name, :presence => true
  validates :course_id, :presence => true
  validates :user_id, :presence => true
  
  mount_uploader :file, PresentationUploader
  
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :notebooks
   
  has_many :shares, :dependent => :destroy
    
  accepts_nested_attributes_for :shares, :reject_if => lambda { |a| a[:shared_ids].blank? }
    
  validates :title, :presence => true
  validates :notebook_id, :presence => true
  validates :user_id, :presence => true
  
  def to_param
    "#{id}-#{title.parameterize}"
  end

  def build_shares_from_list(ids)
    ids.each do |id|
      id = id.to_i
      @share = self.shares.build({:shared_ids => id})
      @share.save
    end
  end

end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :user
  has_many :lessons, :dependent => :destroy
  
  # send id & title as url param
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  belongs_to :lesson
end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :shared_token, :shared_ids
  belongs_to :lesson
  
  attr_reader :shared_token
  #serialize :shared_ids
  # TODO: save each seperately #
  def shared_token=(ids)
    #self.shared_ids = ids.split(",")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. 
  # Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  
  after_destroy :ensure_an_admin_remains
  
  has_many :notebooks
  has_many :courses
  has_many :lessons, :through => :notebooks
  has_many :course_lessons, :through => :courses
  
  after_create :send_welcome_mail
  # TODO: Need to decide if this should be added.
  ## after_create :create_default_notebook
  
  private
    def send_welcome_mail
      UserMailer.welcome_email(self.email, self.name).deliver
    end
  
    def create_default_notebook
      if self.role == "student"
        default = Notebook.new
        default.user_id = self.id
        default.name = "#{self.name} default notebook"
        default.save
      end
    end
    def ensure_an_admin_remains
      if User.find_by_admin(true)
        raise "Can't delete admin user"
      end
    end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course_lesson
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @user = current_user
    if @user.admin?
      @users_count = User.count
      @notebooks_count = Notebook.count
      @lessons_count = Lesson.count
      @sign_ins = User.where("sign_in_count > 2").count
    else
      redirect_to profile_path
    end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to(profile_path) unless !signed_in?
    @lessons_count = Lesson.count
    @users_count = User.count
    @notebooks_count = Notebook.count
    @share_count = Share.count
    @title = "The home of studyers"
  end

  def about
    @title = "About Us"
  end

  def contact
    @title = "Contact Us"
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Studyers"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def current_class?(test_path)
    return 'active' if current_page?(test_path)
  end
  
  def user_notebooks
    return current_user.notebooks.order("updated_at DESC")
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def role?(user)
    return user.role
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # def sign_in(user)
  #     cookies.permanent.signed[:remember_token] = [user.id, user.salt]
  #     current_user = user
  #   end
  #   
  #   def current_user
  #     @current_user ||= user_from_remember_token
  #   end
  #   
  #   def signed_in?
  #     !current_user.nil?
  #   end
  #   
  #   def sign_out
  #     cookies.delete(:remember_token)
  #     current_user = nil
  #   end
  #   
  #   def deny_access
  #     redirect_to signin_path, :notice => "Please sign in to access this page."
  #   end
  #   
  #   def current_user?(user)
  #     user == current_user
  #   end
  #   
  #   def redirect_back_or(default)
  #     redirect_to(session[:return_to] || default)
  #     clear_return_to
  #   end
  # 
  #   private
  # 
  #     def user_from_remember_token
  #       User.authenticate_with_salt(*remember_token)
  #     end
  # 
  #     def remember_token
  #       cookies.signed[:remember_token] || [nil, nil]
  #     end
  #   
  #     def store_location
  #       session[:return_to] = request.fullpath
  #     end
  # 
  #     def clear_return_to
  #       session[:return_to] = nil
  #     end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {})
    options = { :size => 120 }.merge(options)
    options[:default] = image_path("http://studyers.com/assets/default_icon.jpg")
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/admin/index.html.erb
Hello master, <br />
you have <%= @users_count %> users.
They have created <%= @lessons_count %> lessons in <%= @notebooks_count %> notebooks. <br />
<%= @sign_ins %> users signed in more than once. <br />
Keep up the good work :)

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="beautifier"></div>
  <div class="container">
    <% if (controller.controller_name == "pages")%>
    <div class="fo_sq">
      <a href="https://github.com/studyers/Studyers">
        <%= image_tag("ForkMe_Wht.png") %> 
      </a>
      <div style="margin: -90px 0px 0px 90px; color: white;">
        Studyers is an open source project. Help us make it better.</div>
      </div>
    <div class="fo_sq">
      
    </div>
    <div class="fo_sq">
      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
        version: 2,
        type: 'profile',
        rpp: 4,
        interval: 30000,
        width: 220,
        height: 250,
        theme: {
          shell: {
            background: '#1a414e',
            color: '#ffffff'
          },
          tweets: {
            background: '#1a414e',
            color: '#ffffff',
            links: '#747373'
          }
        },
        features: {
          scrollbar: false,
          loop: false,
          live: true,
          behavior: 'all'
        }
      }).render().setUser('studyers').start();
      </script>
    </div>
    <div class="fo_sq">
      <h3>Connect with us</h3>
      <%= link_to image_tag("facebook.png"), "http://www.facebook.com/studyers" %>
      <%= link_to image_tag("twitter.png"), "http://www.twitter.com/studyers" %>
      <%= link_to image_tag("wordpress.png"), "http://studyers.wordpress.com/" %>
    </div>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="topbar">
  <div class="bl_de"></div>
  <div class="gr_de"></div>
  <div class="container">
    <div id="logo"><%= link_to image_tag("Studyers_logo.png"), root_path %></div>
    <% if current_user %>
      <div class="user_info user">
        <div class="user_name logged_in"><%= gravatar_for current_user, :size => 17 %><%=t :hi %>, <span><%= link_to current_user.name, profile_path %></span></div>
        <div class="notebooks-title logged_in"><%= link_to t(:notebooks), notebooks_path %></div>
        <div class="lessons-shared logged_in"><%= link_to t(:lessons_shared), lessons_shared_path %></div>
        <% if (!current_user.study_at or current_user.study_at.empty?) and (!current_user.major or current_user.major.empty?) %>
          <div class="user_settings logged_in"><%= link_to t(:complete_profile), edit_user_path(current_user), :class => "noprofile" %></div>
        <% else %>
          <div class="user_settings logged_in"><%= link_to t(:settings), edit_user_path(current_user) %></div>
        <% end %>
        <div class="user_logout logged_in"><%= link_to t(:logout), destroy_user_session_path, :method => :delete %></div>
      </div>
      
    <% else %>
      <div class="user_info">
        <div class="hm-shw-frm">Existing user? <span>Sign in</span></div>
        <%= form_for("user", :html => {:class => "home-signin-form"}, :url => user_session_path) do |f| %>
          <div class="field">
            <%= f.email_field :email, :class => "email-field login-input-field", :placeholder => "email address" %>
          </div>

          <div class="field">
            <%= f.password_field :password, :class => "passwd-field login-input-field" %>
          </div>

          <div class="signin-button"><%= f.submit t(:sign_in), :class => "btn signin" %></div>
          
          <div class="field remember"><%= f.check_box :remember_me %> <%= f.label t(:remember_me) %></div>
        <% end %>
      
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= controller.controller_name %> <%= controller.action_name %> ">
<head>
  <title><%= title %></title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag 'application' %>
  <% if I18n.locale.to_s == 'he' %>
    <%= stylesheet_link_tag 'application_rtl' %>
  <% end %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
  <%= stylesheet_link_tag "application_print", :media => "print" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  
  <% 
    ##
    # Integration to Google Analytics
    # Add your ID via config/studyers.yml
    ##
  %>
  <script type="text/javascript">
    
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= STUDYERS_CONFIG['ganalytics'] %>']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %> <%= I18n.locale %>">
  <%= render 'layouts/header' %>
  <section class="content">
    <% flash.each do |key, value| %>
      <div class="alert-message <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>		
  </section>
  <%= render 'layouts/footer' %>
  <% if controller.controller_name != "pages" && Rails.env != "development" %>
  <% 
    ##
    # Integration to User Voice
    # Add your ID via config/studyers.yml
    ##
  %>
  <script type="text/javascript">
    var uvOptions = {};
    (function() {
      var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
      uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/<%= STUDYERS_CONFIG['uservoice'] %>' ;
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
    })();
  </script>
  <% end %>
</body>
</html>

app/views/pages/about.html.erb
About

app/views/pages/contact.html.erb
Contact

app/views/pages/home.html.erb
<div class="tp_spl">
  <div class="container">
    <div class="tp_text">
      <div id="tp_text_spl">
        <div id="slogan">Create & <span>Share</span> lesson notes</div> 
      </div>
      <%= form_for("user", :html => {:class => "home-signup-form"}, :url => user_registration_path) do |f| %>
        Signing up is free and easy!
        <div class="field">
          <%= f.text_field :name,:placeholder => "Your name" %>
        </div>
        <div class="field">
          <%= f.email_field :email, :placeholder => "Email address" %>
        </div>
        <div class="field">
          <%= f.password_field :password, :placeholder => "Password", :autocomplete => "off" %>
        </div>
        <div class="field">
          <%# f.label :role, "I am a" %>
          <%# f.radio_button :role, 'student', :default => true %> <!-- Student -->
          <%# f.radio_button :role, 'teacher' %> <!-- Teacher -->
        </div>

        <div class="save"><%= f.submit "Start taking notes!", :class => "primary", :id => "home-signup" %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="home_main" style="display: none;">
  <div class="container">
    <div class="span3">
      <div class="title first">
        <h2>Easiest note taking</h2>
      </div>
      <div class="content">
        <%# image_tag("take_notes.png") %>
        With Studyers you can: <br />
        - Add lecturer's presentation <br />
        - Write down notes <br />
        - Draw and add graphs <br />
      
      </div>
    </div>
    <div class="span3">
      <div class="title middle">
        <h2>Sharing notes</h2>
      </div>
      <div class="content">
        <%# image_tag("share_notes.png") %>
        It is now easy to share notes, study together and enrich each other.
      </div>
    </div>
    <div class="span3">
      <div class="title last">
        <h2>Private Studyers</h2>
      </div>
      <div class="content">
        <%# image_tag("organize_lessons.png") %>
        Want a private hosted Studyers for your college?
        Questions? More information? <br />
        Contact us: <a href="mailto:alpha@studyers.com">alpha@studyers.com</a>
      </div>
    </div>
  </div>
</div>